package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate joinPredicate;
    private OpIterator opIterator1, opIterator2;
    private ArrayList<OpIterator> children = new ArrayList<>();
    private boolean tuple2Done;
    private Tuple tuple1;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     *
     * @param p      The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    public Join(final JoinPredicate p, final OpIterator child1, final OpIterator child2) {
        joinPredicate = p;
        opIterator1 = child1;
        opIterator2 = child2;
        children.add(child1);
        children.add(child2);
    }

    public JoinPredicate getJoinPredicate() {
        return joinPredicate;
    }

    /**
     * @return the field name of join field1. Should be quantified by
     * alias or table name.
     */
    public String getJoinField1Name() {
        return opIterator1.getTupleDesc().getFieldName(joinPredicate.getField1());
    }

    /**
     * @return the field name of join field2. Should be quantified by
     * alias or table name.
     */
    public String getJoinField2Name() {
        return opIterator2.getTupleDesc().getFieldName(joinPredicate.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     * implementation logic.
     */
    public TupleDesc getTupleDesc() {
        return TupleDesc.merge(opIterator1.getTupleDesc(), opIterator2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        super.open();
        opIterator1.open();
        opIterator2.open();
        tuple2Done = true;
        tuple1 = null;
    }

    public void close() {
        super.close();
        opIterator1.close();
        opIterator2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        close();
        open();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        final Tuple mergedTuple = new Tuple(getTupleDesc());
        while (opIterator1.hasNext() || !tuple2Done) {
            if (tuple2Done) {
                tuple1 = opIterator1.next();
            }
            tuple2Done = false;
            while (opIterator2.hasNext()) {
                final Tuple tuple2 = opIterator2.next();
                if (joinPredicate.filter(tuple1, tuple2)) {
                    int index = 0;
                    final Iterator<Field> fields1 = tuple1.fields();
                    while (fields1.hasNext()) {
                        mergedTuple.setField(index, fields1.next());
                        index += 1;
                    }
                    final Iterator<Field> fields2 = tuple2.fields();
                    while (fields2.hasNext()) {
                        mergedTuple.setField(index, fields2.next());
                        index += 1;
                    }
                    return mergedTuple;
                }
            }
            tuple2Done = true;
            opIterator2.rewind();
        }
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        return children.toArray(OpIterator[]::new);
    }

    @Override
    public void setChildren(final OpIterator[] children) {
        this.children = (ArrayList<OpIterator>) Arrays.asList(children);
    }

}
